#! /bin/bash

#train
MODEL_PRED="PATH_TO_MODEL_DIR"
BASELINE_PRED="PATH_TO_MODEL_DIR"
RESULT_PATH="../analysis/Results"
DOMAIN="train"

SAMPLE_COUNT="1000"
SLOTS=""

python analysis.py my_model baseline $MODEL_PRED $BASELINE_PRED $RESULT_PATH $DOMAIN $SAMPLE_COUNT $SLOTS