SAVE_DIR="PATH_TO_SAVE_DIR"
python src/attention_viz.py \
    --wandb_mode offline \
    --wandb_run_name none_run \
    --n_epochs 1000 \
    --seed 557 \
    --train_batch_size 2 \
    --GPU 1 \
    --gpu_id 0 \
    --except_domain train \
    --slot_lang question \
    --saving_dir debugger_saved \
    --warm_up_steps 1 \
    --worker_number 0 \
    --gradient_accumulation_steps 1 \
    --T5_checkpoint ../save/models/small \
    --max_size 500 \
    --no_early_stop \
    --prefix_length 10 \
    --prompter_dropout 0.2 \
    --model_checkpoint $SAVE_DIR